version: '2'

volumes:
  mos-config:
  ad-config:
  ha-config:
  debuger-config:

networks:
  internal:

services:

  mos:
    container_name: mosquitto
    image: arm32v6/eclipse-mosquitto
    ports:
      - 8883:8883
    volumes:
      - mos-config:/mosquitto/config
    restart: always
    # network_mode: bridge
    networks:
      internal:

    environment:
      - TZ=Europe/London

  ha:
    container_name: home-assistant
    image: homeassistant/raspberrypi3-homeassistant:stable
    ports:
      - 80:8123
    volumes:
      - ha-config:/config
    environment:
      - TZ=Europe/London
    restart: always
    # network_mode: bridge
    networks:
      internal:
    depends_on:
      - mos

  ad:
    container_name: appdaemon
    build:
      dockerfile: AppDaemon.Dockerfile
      context: .
    # network_mode: bridge
    networks:
      internal:
    volumes:
      - ad-config:/conf
    restart: always
    environment:
      - TZ=Europe/London
    depends_on:
      - ha
    # command: ["appdaemon", "-c", "/conf", "-D", "DEBUG"]

  ddns:
    container_name: ddns
    restart: on-failure
    build:
      dockerfile: ddns.Dockerfile
      context: .
    # network_mode: bridge
    networks:
      internal:
    # volumes:

    labels:
      io.balena.features.supervisor-api: '1'
